=== Cozy-Finance/protection-market-lists/src/protectionmarketlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "DivestScript": {
      "properties": {
        "address": {
          "type": "string"
        },
        "signature": {
          "enum": [
            "function divest(uint256[] amounts, address recipient, uint256[] claimRewards)"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "InvestScript": {
      "properties": {
        "address": {
          "type": "string"
        },
        "signature": {
          "enum": ["function invest(uint256[] amounts, uint256[] approve)"],
          "type": "string"
        }
      },
      "type": "object"
    },
    "InvestmentOpportunity": {
      "properties": {
        "dataURI": {
          "type": "string"
        },
        "divest": {
          "$ref": "#/definitions/DivestScript"
        },
        "invest": {
          "$ref": "#/definitions/InvestScript"
        },
        "strategy": {
          "items": {
            "$ref": "#/definitions/StrategyLeg"
          },
          "type": "array"
        },
        "tokens": {
          "properties": {
            "input": {
              "items": {
                "$ref": "#/definitions/TokenInfo"
              },
              "type": "array"
            },
            "receipt": {
              "items": {
                "$ref": "#/definitions/TokenInfo"
              },
              "type": "array"
            },
            "rewards": {
              "items": {
                "$ref": "#/definitions/TokenInfo"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "ProtectionMarketInfo": {
      "properties": {
        "address": {
          "type": "string"
        },
        "chainId": {
          "type": "number"
        },
        "decimals": {
          "type": "number"
        },
        "extensions": {
          "additionalProperties": {
            "type": ["null", "string", "number", "boolean"]
          },
          "type": "object"
        },
        "investmentOpportunity": {
          "$ref": "#/definitions/InvestmentOpportunity"
        },
        "isTriggered": {
          "type": "boolean"
        },
        "logoURI": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "trigger": {
          "type": "string"
        },
        "underlying": {
          "$ref": "#/definitions/TokenInfo"
        }
      },
      "type": "object"
    },
    "StrategyLeg": {
      "properties": {
        "action": {
          "enum": ["Borrow", "Deposit to", "Stake on"],
          "type": "string"
        },
        "destination": {
          "type": "number"
        },
        "logoURI": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Tags": {
      "additionalProperties": {
        "properties": {
          "description": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "object"
    },
    "TokenInfo": {
      "properties": {
        "address": {
          "type": "string"
        },
        "chainId": {
          "type": "number"
        },
        "decimals": {
          "type": "number"
        },
        "extensions": {
          "additionalProperties": {
            "type": ["null", "string", "number", "boolean"]
          },
          "type": "object"
        },
        "logoURI": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Version": {
      "properties": {
        "major": {
          "type": "number"
        },
        "minor": {
          "type": "number"
        },
        "patch": {
          "type": "number"
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "keywords": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "logoURI": {
      "type": "string"
    },
    "markets": {
      "items": {
        "$ref": "#/definitions/ProtectionMarketInfo"
      },
      "type": "array"
    },
    "name": {
      "type": "string"
    },
    "tags": {
      "$ref": "#/definitions/Tags"
    },
    "timestamp": {
      "type": "string"
    },
    "version": {
      "$ref": "#/definitions/Version"
    }
  },
  "type": "object"
}

=== Cozy-Finance/protection-market-lists/test/schema/invaliddecimals.1.tokenlist.json
{
  "name": "My Protection Market List",
  "timestamp": "2021-09-01T00:00:00+00:00",
  "markets": [
    {
      "chainId": 1,
      "address": "0xdBDF2fC3Af896e18f2A9DC58883d12484202b57E",
      "symbol": "cozyUSDC",
      "name": "Cozy USD Coin",
      "decimals": 256,
      "logoURI": "https://raw.githubusercontent.com/compound-finance/token-list/master/assets/asset_USDC.svg",
      "tags": ["stablecoin", "money market"],
      "trigger": "0x0000000000000000000000000000000000000000",
      "isTriggered": false,
      "underlying": {
        "chainId": 1,
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "symbol": "USDC",
        "name": "USD Coin",
        "decimals": 6,
        "logoURI": "https://raw.githubusercontent.com/compound-finance/token-list/master/assets/asset_USDC.svg",
        "tags": ["stablecoin"]
      }
    },
    {
      "chainId": 1,
      "address": "0x9affB6D8568cEfa2837d251b1553967430D1a5e5",
      "symbol": "Cozy-USDC-2",
      "name": "Cozy-USDC-2-Yearn USDC V2 Vault Share Price Trigger",
      "decimals": 8,
      "logoURI": "https://compound.finance/compound-components/assets/asset_YFI.svg",
      "tags": ["stablecoin", "protection market"],
      "trigger": "0x02E57c5800a345Fe97d73fA8bB72B948E19aA499",
      "isTriggered": false,
      "underlying": {
        "chainId": 1,
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "symbol": "USDC",
        "name": "USD Coin",
        "decimals": 6,
        "logoURI": "https://raw.githubusercontent.com/compound-finance/token-list/master/assets/asset_USDC.svg",
        "tags": ["stablecoin"]
      }
    }
  ],
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  }
}

=== Cozy-Finance/protection-market-lists/test/schema/exampleminimum.protectionmarketlist.json
{
  "name": "My Token List",
  "timestamp": "2020-06-12T00:00:00+00:00",
  "markets": [
    {
      "chainId": 1,
      "address": "0xdBDF2fC3Af896e18f2A9DC58883d12484202b57E",
      "symbol": "cozyUSDC",
      "name": "Cozy USD Coin",
      "decimals": 8,
      "trigger": "0x0000000000000000000000000000000000000000",
      "isTriggered": false,
      "underlying": {
        "chainId": 1,
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "symbol": "USDC",
        "name": "USD Coin",
        "decimals": 6
      }
    }
  ],
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  }
}
